app = "sf-rec"
primary_region = "sjc"

[build]
dockerfile = "Dockerfile"

[env]
PYTHONUNBUFFERED = "1"

[deploy]
strategy = "immediate"

[processes]
app = "uv run -m scheduler"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[experimental]
allowed_public_ports = []
auto_rollback = true

[metrics]
path = "/metrics"
port = 9091
