app = "sf-rec" 
primary_region = "sjc" # San Jose, CA

[build]
dockerfile = "Dockerfile"

[env]
PYTHONUNBUFFERED = "1"

[deploy]
strategy = "immediate"

[processes]
app = "python -m scheduler"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
